[
  {
    id: 0,
    name: "Screwdriver",
    strength: "10%",
    img: "img/screwdriver 1.svg",
    citron: "true",
    ice: "true",
    shaker: "true",
    approach: [
      "Grab your cocktail shaker and put in your desired amount of Vodka, Orange juice and ice cubes.",
      "hej step 1",
      "hej step 2",
    ],
    favorite: "",
    categories: ["Poolside", "Tropical", "Vodka"],
    ingredients: [
      {
        name: "Vodka",
        amount: 5,
        category: "liqueurs",
      },
      {
        name: "Orange juice",
        amount: 10,
        category: "juice",
      },
    ],
    difficulty: 1,
  },
  {
    id: 1,
    name: "Gin Hass",
    strength: "12%",
    img: "img/appleCider 1.svg",
    citron: "true",
    ice: "true",
    shaker: "false",
    approach: ["hej step 1", "hej step 2"],
    favorite: "",
    ingredients: [
      {
        name: "Gin",
        amount: 4,
        category: "alcohol",
      },
      {
        name: "Lime juice",
        amount: 2,
        category: "juice",
      },
      {
        name: "Mango syrup",
        amount: 2,
        category: "syrup",
      },
      {
        name: "Lemon soda",
        amount: 8,
        category: "soda",
      },
    ],
    difficulty: 3,
  },
  {
    id: 2,
    name: "Tequila Sunrise",
    strength: "9%",
    img: "img/limoncellaMule 1.svg",
    citron: "true",
    ice: "true",
    shaker: "true",
    approach: ["hej step 1", "hej step 2"],
    favorite: "",
    ingredients: [
      {
        name: "Tequila",
        amount: 4,
        category: "alcohol",
      },
      {
        name: "Grenadine",
        amount: 2,
        category: "syrup",
      },
      {
        name: "Orange juice",
        amount: 10,
        category: "juice",
      },
    ],
    difficulty: 2,
  },
  {
    id: 3,
    name: "Black Russian",
    strength: "24%",
    img: "img/creamy 1.svg",
    citron: "false",
    ice: "true",
    shaker: "false",
    approach: ["hej step 1", "hej step 2"],
    favorite: "",
    ingredients: [
      {
        name: "Vodka",
        amount: 10,
        category: "alcohol",
      },
      {
        name: "Coffee Liqueur",
        amount: 5,
        category: "liqueur",
      },
    ],
    difficulty: 1,
  },
  {
    id: 4,
    name: "White Russian",
    strength: "10%",
    img: "img/whiteRussian 1.svg",
    citron: "false",
    ice: "true",
    shaker: "true",
    approach: ["hej step 1", "hej step 2"],
    favorite: "",
    ingredients: [
      {
        name: "Vodka",
        amount: 4,
        category: "alcohol",
      },
      {
        name: "Kahlua",
        amount: 3,
        category: "liqeuer",
      },
      {
        name: "Milk",
        amount: 8,
        category: "dairy",
      },
    ],
    difficulty: 3,
  },
  {
    id: 5,
    name: "Aperol Spritz",
    strength: "10%",
    img: "img/AperolSpritz.svg",
    citron: "false",
    ice: "true",
    shaker: "false",
    approach: ["hej step 1", "hej step 2"],
    favorite: "",
    ingredients: [
      {
        name: "Aperol",
        amount: 5,
        category: "liqueur",
      },
      {
        name: "Prosecco",
        amount: 5,
        category: "wine",
      },
      {
        name: "Club Soda",
        amount: 1,
        category: "soda",
      },
    ],
    difficulty: 2,
  },
  {
    id: 6,
    name: "Dry Martini",
    strength: "26%",
    img: "img/martini 1.svg",
    citron: "true",
    ice: "true",
    shaker: "true",
    approach: [
      "Grab your cocktail shaker and fill it with ice, dry Vermouth and dry Gin. Shake, pour into a Martini glass and top with a slice of lemon. Shaken, not stirred please.",
      "hej step 1",
      "hej step 2",
    ],
    favorite: "",
    categories: ["Poolside", "Gin", "Birthday"],
    ingredients: [
      {
        name: "Gin",
        amount: 6,
        category: "liqueurs",
      },
      {
        name: "Dry Vermouth",
        amount: 0.5,
        category: "wines",
      },
    ],
    difficulty: 2,
  },
  {
    id: 7,
    name: "Limoncella Mule",
    strength: "15%",
    img: "img/limoncellaMule 1.svg",
    citron: "true",
    ice: "true",
    shaker: "false",
    approach: [
      "Grab a glass and fill it with ice cubes. Pour Limoncello, Vodka into the glass and top off with Ginger beer.",
      "hej step 1",
      "hej step 2",
    ],
    favorite: "",
    categories: ["Poolside", "Vodka", "Movie Night"],
    ingredients: [
      {
        name: "Vodka",
        amount: 2,
        category: "liqueurs",
      },
      {
        name: "Limoncello",
        amount: 2,
        category: "liqueurs",
      },
      {
        name: "Ginger Beer",
        amount: 10,
        category: "soda",
      },
    ],
    difficulty: 2,
  },
  {
    id: 8,
    name: "Raspberry Cosmopolitan",
    strength: "15%",
    img: "img/rasberryCosmopolitan 1.svg",
    citron: "true",
    ice: "true",
    shaker: "true",
    approach: [
      "Grab your cocktail shaker and fill it with all the ingredients. Shake and pour into a glass with ice cubes. Garnish with a slice of lemon.",
      "hej step 1",
      "hej step 2",
    ],
    favorite: "",
    categories: ["Tropical", "Vodka", "Birthday"],
    ingredients: [
      {
        name: "Vodka",
        amount: 5,
        category: "liqueurs",
      },
      {
        name: "Cointreau",
        amount: 3,
        category: "liqueurs",
      },
      {
        name: "Lime juice",
        amount: 1,
        category: "juice",
      },
      {
        name: "Cranberry juice",
        amount: 8,
        category: "juice",
      },
    ],
    difficulty: 5,
  },
  {
    id: 9,
    name: "French 75",
    strength: "15%",
    img: "img/icelandicLady 1.svg",
    citron: "true",
    ice: "true",
    shaker: "true",
    approach: [
      "Grab your cocktail shaker and fill it with all the ingredients. Shake and pour into a glass with ice cubes. Garnish with a slice of lemon.",
      "hej step 1",
      "hej step 2",
    ],
    favorite: "",
    categories: ["Tropical", "Gin", "Birthday"],
    ingredients: [
      {
        name: "Gin",
        amount: 4,
        category: "liqueurs",
      },
      {
        name: "Lemon juice",
        amount: 2,
        category: "juice",
      },
      {
        name: "Sugar syrup",
        amount: 2,
        category: "syrup",
      },
      {
        name: "Champagne",
        amount: 8,
        category: "wines",
      },
    ],
    difficulty: 5,
  },
];
