[
  {
    name: "Screwdriver",
    strength: "10%",
    img: "url",
    citron: "true",
    ice: "true",
    shaker: "true",
    approach: ["hej step 1", "hej step 2"],
    favorite: "",
    ingredients: [
      {
        name: "Vodka",
        amount: 5,
        category: "alcohol",
      },
      {
        name: "Orange juice",
        amount: 10,
        category: "juice",
      },
    ],
    difficulty: 1,
  },
  {
    name: "Gin Hass",
    strength: "12%",
    img: "url",
    citron: "true",
    ice: "true",
    shaker: "false",
    approach: ["hej step 1", "hej step 2"],
    favorite: "",
    ingredients: [
      {
        name: "Gin",
        amount: 4,
        category: "alcohol",
      },
      {
        name: "Lime juice",
        amount: 2,
        category: "juice",
      },
      {
        name: "Mango syrup",
        amount: 2,
        category: "syrup",
      },
      {
        name: "Lemon soda",
        amount: 8,
        category: "soda",
      },
    ],
    difficulty: 3,
  },
  {
    name: "Tequila Sunrise",
    strength: "9%",
    img: "url",
    citron: "true",
    ice: "true",
    shaker: "true",
    approach: ["hej step 1", "hej step 2"],
    favorite: "",
    ingredients: [
      {
        name: "Tequila",
        amount: 4,
        category: "alcohol",
      },
      {
        name: "Grenadine",
        amount: 2,
        category: "syrup",
      },
      {
        name: "Orange juice",
        amount: 10,
        category: "juice",
      },
    ],
    difficulty: 2,
  },
  {
    name: "Black Russian",
    strength: "24%",
    img: "url",
    citron: "false",
    ice: "true",
    shaker: "false",
    approach: ["hej step 1", "hej step 2"],
    favorite: "",
    ingredients: [
      {
        name: "Vodka",
        amount: 10,
        category: "alcohol",
      },
      {
        name: "Coffee Liqueur",
        amount: 5,
        category: "liqueur",
      },
    ],
    difficulty: 1,
  },
  {
    name: "White Russian",
    strength: "10%",
    img: "url",
    citron: "false",
    ice: "true",
    shaker: "true",
    approach: ["hej step 1", "hej step 2"],
    favorite: "",
    ingredients: [
      {
        name: "Vodka",
        amount: 4,
        category: "alcohol",
      },
      {
        name: "Coffee Liqueur",
        amount: 3,
        category: "liqeuer",
      },
      {
        name: "Milk",
        amount: 8,
        category: "dairy",
      },
    ],
    difficulty: 3,
  },
  {
    name: "Aperol Spritz",
    strength: "10%",
    img: "url",
    citron: "false",
    ice: "true",
    shaker: "false",
    approach: ["hej step 1", "hej step 2"],
    favorite: "",
    ingredients: [
      {
        name: "Aperol",
        amount: 5,
        category: "liqueur",
      },
      {
        name: "Prosecco",
        amount: 5,
        category: "wine",
      },
      {
        name: "Club Soda",
        amount: 1,
        category: "soda",
      },
    ],
    difficulty: 2,
  },
];
